const listGenre = [
    "Fiction",
    "Non-fiction",
    "Science Fiction",
    "Fantasy",
    "Mystery",
    "Thriller",
    "Horror",
    "Romance",
    "Historical Fiction",
    "Biography",
    "Autobiography",
    "Memoir",
    "Self-help",
    "Poetry",
    "Drama",
    "Comedy",
    "Satire",
    "Adventure",
    "Children's",
    "Young Adult",
    "Science",
    "History",
    "Art",
    "Travel",
    "Cooking",
    "Health",
    "Fitness",
    "Technology",
    "Business",
    "Philosophy"
];

export default listGenre;